services:
  db:
    image: postgres:16
    container_name: myapp-db
    environment:
      POSTGRES_DB: educatalog
      POSTGRES_USER: educatalog
      POSTGRES_PASSWORD: supersecurepassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
